var resData = [
	{
		"name":"bg_jpg",
		"type":"image",
		"url":"images/bg.jpg"
	},
	{
		"name":"buy1_png",
		"type":"image",
		"url":"images/buy1.png"
	},
	{
		"name":"buy1_disable_png",
		"type":"image",
		"url":"images/buy1_disable.png"
	},
	{
		"name":"buy1_disable_btn_png",
		"type":"image",
		"url":"images/buy1_disable_btn.png"
	},
	{
		"name":"buy2_png",
		"type":"image",
		"url":"images/buy2.png"
	},
	{
		"name":"buy2_disable_png",
		"type":"image",
		"url":"images/buy2_disable.png"
	},
	{
		"name":"cakebox_png",
		"type":"image",
		"url":"images/cakebox.png"
	},
	{
		"name":"cakemid_png",
		"type":"image",
		"url":"images/cakemid.png"
	},
	{
		"name":"caketop_png",
		"type":"image",
		"url":"images/caketop.png"
	},
	{
		"name":"flat_png",
		"type":"image",
		"url":"images/flat.png"
	},
	{
		"name":"flow_png",
		"type":"image",
		"url":"images/flow.png"
	},
	{
		"name":"flow2_png",
		"type":"image",
		"url":"images/flow2.png"
	},
	{
		"name":"flow3_png",
		"type":"image",
		"url":"images/flow3.png"
	},
	{
		"name":"flowers_png",
		"type":"image",
		"url":"images/flowers.png"
	},
	{
		"name":"rules_png",
		"type":"image",
		"url":"images/rules.png"
	},
	{
		"name":"vsop_png",
		"type":"image",
		"url":"images/vsop.png"
	},
	{
		"name":"spoon_png",
		"type":"image",
		"url":"images/spoon.png"
	},
	{
		"name":"title_png",
		"type":"image",
		"url":"images/title.png"
	},
	{
		"name":"wine_png",
		"type":"image",
		"url":"images/wine.png"
	},
	{
		"name":"chocolate_png",
		"type":"image",
		"url":"images/chocolate.png"
	}]